PROMPT_SUFFIX_IDEAS = [
    "Oil on canvas",
    "Acrylic on canvas",
    "Watercolor on paper",
    "Ink on paper",
    "Graphite on paper",
    "Charcoal on paper",
    "Pastel on paper",
    "Pencil on paper",
    "Oil on paper",
    "Acrylic on paper",
    "Watercolor on canvas",
    "Ink on canvas",
    "Graphite on canvas",
    "Charcoal on canvas",
    "Pastel on canvas",
    "Pencil on canvas",
    "Oil on canvas",
    "Acrylic on canvas",
    "Hyper-realistic sculpture",
    "Photorealistic sculpture",
    "Hyper-realistic painting",
    "Photorealistic painting",
    "Hyper-realistic drawing",
    "Photorealistic drawing",
    "Hyper-realistic print",
    "Photorealistic print",
    "Hyper-realistic photograph",
    "Photorealistic photograph",
    "Woodcut",
    "Lithograph",
    "Etching",
    "Screenprint",
    "Digital print",
    "Digital painting",
    "Digital drawing",
    "Shot on film",
    "Shot on digital",
    "Shot on video",
    "Shot on 35mm",
    "Shot on 16mm",
    "Shot on 8mm",
    "posted on Instagram",
    "posted on Facebook",
    "posted on Twitter",
    "posted on Tumblr",
    "posted on Flickr",
    "posted on Pinterest",
    "posted on Reddit",
    "posted on 4chan",
    "posted on 8chan",
    "posted on 9gag",
    "as a GIF",
    "as a JPEG",
    "as a PNG",
    "as a TIFF",
    "as a BMP",
    "with a 90s filter",
    "with an 80s filter",
    "with a 70s filter",
    "with a 60s filter",
    "with a 50s filter",
    "Sci-fi",
    "Fantasy",
    "Horror",
    "Action",
    "Adventure",
    "Comedy",
    "Drama",
    "Romance",
    "in the style of a 90s sitcom",
    "where the img2img character is a cat",
    "where the img2img character is a dog",
    "where the img2img character is a bird",
    "where the img2img character is a fish",
    "where the img2img character is a reptile",
    "during the apocalypse",
    "during a zombie apocalypse",
    "during a nuclear apocalypse",
    "during a pandemic",
    "during a plague",
    "during a war",
    "life in the future",
    "life in the past",
    "life in the present",
    "Monochrome",
    "Tri-tone",
    "Quad-tone",
    "Pent-tone",
    "Hex-tone",
    "Indie",
    "Industrial",
]
PROMPT_PREFIX_IDEAS = [
    "Abstract art in the style of George Condo",
    "Abstract art in the style of Jackson Pollock",
    "Abstract art in the style of Mark Rothko",
    "Abstract art in the style of Piet Mondrian",
    "Abstract art in the style of Wassily Kandinsky",
    "Abstract art in the style of Willem de Kooning",
    "Abstract art in the style of Yves Klein",
    "Abstract art in the style of Zao Wou-Ki",
    "Impressionist art in the style of Claude Monet",
    "Impressionist art in the style of Edgar Degas",
    "Impressionist art in the style of Edouard Manet",
    "Impressionist art in the style of Pierre-Auguste Renoir",
    "Impressionist art in the style of Vincent van Gogh",
    "Post-impressionist art in the style of Paul Cézanne",
    "Post-impressionist art in the style of Paul Gauguin",
    "Post-impressionist art in the style of Paul Signac",
    "Post-impressionist art in the style of Pierre-Auguste Renoir",
    "Post-impressionist art in the style of Vincent van Gogh",
    "Realism art in the style of Édouard Manet",
    "Realism art in the style of Gustave Courbet",
    "Realism art in the style of Honoré Daumier",
    "Realism art in the style of Jean-François Millet",
    "Realism art in the style of Jean-Auguste-Dominique Ingres",
    "Realism art in the style of Jean-Baptiste-Camille Corot",
    "Classical art in the style of Michelangelo",
    "Classical art in the style of Raphael",
    "Classical art in the style of Rembrandt",
    "Classical art in the style of Rubens",
    "Film noir in the style of Alfred Hitchcock",
    "Film noir in the style of Billy Wilder",
    "Film noir in the style of Orson Welles",
    "Gothic art in the style of Albrecht Dürer",
    "Gothic art in the style of Hieronymus Bosch",
    "Gothic art in the style of Jan van Eyck",
    "Pop art in the style of Andy Warhol",
    "8-bit art in the style of Nintendo",
    "8-bit art in the style of Sega",
    "8-bit art in the style of Atari",
    "8-bit art in the style of Commodore",
    "16-bit art in the style of Nintendo",
    "16-bit art in the style of Sega",
    "16-bit art in the style of Atari",
    "32-bit art in the style of Nintendo",
    "32-bit art in the style of Sega",
    "64-bit art in the style of Nintendo",
    "64-bit art in the style of Sega",
    "Hyper-realistic art in the style of Chuck Close",
    "Hyper-realistic art in the style of Damien Hirst",
    "Hyper-realistic art in the style of George Condo",
    "Hyper-realistic art in the style of Kehinde Wiley",
    "Photorealistic art in the style of Chuck Close",
    "Photorealistic art in the style of Damien Hirst",
    "Futurist art in the style of Umberto Boccioni",
    "Futurist art in the style of Filippo Marinetti",
    "Futurist art in the style of Giacomo Balla",
    "Geometric art in the style of Piet Mondrian",
    "Geometric art in the style of Wassily Kandinsky",
    "Japanese art in the style of Hokusai",
    "Japanese art in the style of Katsushika Hokusai",
    "Japanese art in the style of Katsushika Hokusai",
    "Korean art in the style of Lee Ufan",
    "Latin American art in the style of Frida Kahlo",
    "Latin American art in the style of Diego Rivera",
    "Modern art in the style of Pablo Picasso",
    "Modern art in the style of Henri Matisse",
    "Neo-expressionism in the style of Julian Schnabel",
    "Neo-expressionism in the style of Francesco Clemente",
    "Neo-expressionism in the style of Lucian Freud",
    "Op art in the style of Bridget Riley",
    "Renaissance art in the style of Leonardo da Vinci",
    "Renaissance art in the style of Michelangelo",
    "Surrealism in the style of Salvador Dalí",
    "Surrealism in the style of René Magritte",
    "Tribal art in the style of the Dogon",
    "Tribal art in the style of the Maori",
    "Urban art in the style of Banksy",
    "Urban art in the style of Shepard Fairey",
    "Video game art in the style of Nintendo",
    "Video game art in the style of Sega",
    "Video game art in the style of Atari",
    "Video game art in the style of Capcom",
    "Video game art in the style of Konami",
    "Video game art in the style of Square Enix",
    "Video game art in the style of Ubisoft",
    "Video game art in the style of Blizzard",
    "Video game art in the style of Bethesda",
    "Video game art in the style of Sony",
    "Video game art in the style of Microsoft",
    "Western art in the style of Rembrandt",
    "Western art in the style of Rubens",
    "Western art in the style of Michelangelo",
    "X-ray art in the style of Damien Hirst",
    "Zombie art in the style of George Romero",
    "Zombie art in the style of Lucio Fulci",
    "Comic book art in the style of Marvel",
    "Comic book art in the style of DC",
    "Comic book art in the style of Image",
    "Comic book art in the style of Dark Horse",
    "Comic book art in the style of IDW",
    "Comic book art in the style of Dynamite",
    "Comic book art in the style of Archie",
    "Comic book art in the style of Valiant",
    "Comic book art in the style of Vertigo",
    "Comic book art in the style of Boom!",
    "Comic book art in the style of Dark Horse",
    "Comic book art in the style of Dynamite",
    "Photography in the style of Ansel Adams",
    "Photography in the style of Diane Arbus",
    "Photography in the style of Annie Leibovitz",
    "Photography in the style of Edward Weston",
    "Photography in the style of Henri Cartier-Bresson",
    "Photography in the style of Irving Penn",
]


PROJECT_ID = "33527d88-636b-4833-876d-6d0665d970b5"
